import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import React from "react";
import ClientProvider from "./ClientProvider";

export const metadata: Metadata = {
  title: "Getthawha",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("info")?.value;

  let user = null;
  if (token) {
    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_BASE_URL}/admin/auth/info`,
        {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
            Cookie: token ? `info=${token}` : "",
          },
        }
      );
      if (response.ok) {
        const data = await response.json();
        user = data.user || null;
      }
    } catch (error) {
      console.error("Failed to fetch user info:", error);
    }
  }

  return (
    <html lang="en">
      <body className="antialiased vsc-initialized">
        <ClientProvider
          id={user?.id || ""}
          email={user?.email || ""}
          username={user?.username || ""}
        >
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
